 name: learn-github-actions 
 on: [push]
 jobs:
  build:
   runs-on: ubuntu-latest
   stops:
    -uses: actions/checkout@v2 
    -run: echo "This job was automatically triggered by a ${{ github.event_name }} event."
    -run: pwd
    -run: ls -la
